-- scripts to initailly load the database

CREATE TABLE IF NOT EXISTS BANKACCOUNT(
BANKACCID INT PRIMARY KEY,
SSID VARCHAR(100)
BANKACCHOLDERNAME VARCHAR(250),
BALANCE DECIMAL(20,2) DEFAULT 0.00,
CURRENCYCODE VARCHAR(3) DEFAULT 'GBP',
EMAILID VARCHAR(50),
CONTACT VARCHAR(20),
ACCOUNTTYPE VARCHAR(4) DEFAULT 'SAV'
)

